name: Build and Deploy to GAE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GCP_PROJECT: discord-bartender-263921
  GCP_ZONE: us-central
  GAE_NAME: apps/discord-bartender-263921

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud info
