name: Build and Deploy to GAE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GCP_PROJECT: discord-bartender-263921
  GCP_ZONE: us-central
  GAE_NAME: apps/discord-bartender-263921
  service_account_key: ${{ secrets.GCP_SA_KEY }}
  BARTENDER_CONFIG: ${{ secrets.BARTENDER_CONFIG }}

jobs:
  terraform:
      name: Terraform
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@master

        - name: 'Set Terraform Environment'
          run: |
            # Set Terraform Environment
            echo $service_account_key | base64 -d > tf/account.json

        - name: 'Terraform Format'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.12.18
            tf_actions_working_dir: 'tf/'
            tf_actions_subcommand: 'fmt'

        - name: 'Terraform Init'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.12.18
            tf_actions_working_dir: 'tf/'
            tf_actions_subcommand: 'init'

        - name: 'Terraform Validate'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.12.18
            tf_actions_working_dir: 'tf/'
            tf_actions_subcommand: 'validate'

        - name: 'Terraform Plan'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.12.18
            tf_actions_working_dir: 'tf/'
            tf_actions_subcommand: 'plan'

        - name: 'Terraform Apply'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.12.18
            tf_actions_working_dir: 'tf/'
            tf_actions_subcommand: 'apply'

  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Set project
      run: |
        gcloud config set project $GCP_PROJECT

    - name: Set config
      run: |
        echo $BARTENDER_CONFIG | base64 -d > config.json

    - name: Push GAE App
      run: |
        gcloud app deploy --promote --stop-previous-version --version=bartender-main --quiet
